In [1]:
# Import all the necessary libraries
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectKBest,chi2,RFECV
from imblearn.under_sampling import RandomUnderSampler
from imblearn.combine import SMOTETomek, SMOTEENN

from sklearn.impute import SimpleImputer

from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from sklearn.svm import OneClassSVM
from imblearn.ensemble import BalancedBaggingClassifier
from sklearn.metrics import classification_report, confusion_matrix, mean_squared_error, accuracy_score, f1_score

import joblib

%matplotlib inline



In [2]:
import pandas as pd

In [3]:
# Ignore warnings to see clean output
import warnings
warnings.filterwarnings("ignore")

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
# Load the data
df_FP=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/AI_Club/raw_data/train_data_Total_FP.csv")
df_C=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/AI_Club/raw_data/train_data_Captain.csv")
df_FPT=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/AI_Club/raw_data/test_data_Total_FP (1).csv")
df_CT=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/AI_Club/raw_data/test_data_Captain (1).csv")

In [6]:
# Check the first few rows of the data
df_FP.describe()

match_id        season  batting_innings  bowling_innings  \
count  21616.000000  21616.000000     21616.000000     21616.000000   
mean   11196.635918   2015.633975         1.497641         1.502359   
std     6452.702186      4.663043         0.500006         0.500006   
min        1.000000   2008.000000         1.000000         1.000000   
25%     5611.750000   2012.000000         1.000000         1.000000   
50%    11195.500000   2015.000000         1.000000         2.000000   
75%    16783.250000   2020.000000         2.000000         2.000000   
max    22362.000000   2023.000000         2.000000         2.000000   

       Starting_11     prev_runs    prev_balls    prev_sixes    prev_fours  \
count      21616.0  14699.000000  14699.000000  14699.000000  14699.000000   
mean           4.0     19.622559     15.126267      0.759848      1.776720   
std            0.0     21.306417     13.636834      1.343462      2.307336   
min            4.0      0.000000      0.000000      0.000000      0.000000   
25%            4.0      3.000000      5.000000      0.000000      0.000000   
50%            4.0     12.000000     11.000000      0.000000      1.000000   
75%            4.0     29.000000     22.000000      1.000000      3.000000   
max            4.0    175.000000     73.000000     17.000000     19.000000   

       prev_wickets  prev_conceded  prev_catches  prev_Dream Team  \
count  11335.000000   11335.000000   6682.000000     20939.000000   
mean       0.916542      25.932510      1.022897         0.510292   
std        0.998369      10.675894      0.628788         0.499906   
min        0.000000       0.000000      0.000000         0.000000   
25%        0.000000      18.500000      1.000000         0.000000   
50%        1.000000      26.000000      1.000000         1.000000   
75%        1.000000      33.000000      1.000000         1.000000   
max        6.000000      70.000000      5.000000         1.000000   

       prev_Total_FP    prev_overs  prev_fielding_heroics     prev_duck  \
count   20939.000000  11335.000000            6682.000000  21616.000000   
mean       39.281389      3.236568               0.275367      0.071521   
std        33.193384      1.017250               0.519249      0.257699   
min        -4.000000      0.000000               0.000000      0.000000   
25%        12.000000      3.000000               0.000000      0.000000   
50%        31.000000      4.000000               0.000000      0.000000   
75%        57.000000      4.000000               0.000000      0.000000   
max       306.000000      4.000000               4.000000      1.000000   

               luck      Total_FP  
count  21616.000000  21616.000000  
mean      49.633142     37.617274  
std       28.865971     31.775817  
min        0.000000     -4.000000  
25%       25.000000     12.000000  
50%       50.000000     30.000000  
75%       75.000000     55.000000  
max       99.000000    306.000000

In [7]:
# Check all the columns of the dataframe
df_FP.columns

Index(['match_id', 'season', 'match_name', 'home_team', 'away_team', 'venue',
       'batting_innings', 'bowling_innings', 'Player_name', 'Starting_11',
       'bowling_team_bowl', 'batting_team_bat', 'prev_runs', 'prev_balls',
       'prev_sixes', 'prev_fours', 'prev_wickets', 'prev_conceded',
       'prev_Overs_Bowled', 'prev_catches', 'prev_Dream Team', 'prev_Total_FP',
       'prev_overs', 'prev_fielding_heroics', 'prev_duck', 'luck', 'Total_FP'],
      dtype='object')

In [8]:
# Remove rows with nan values
df_FP = df_FP[df_FP["prev_Total_FP"].notna()]
df_C = df_C[df_C["prev_Total_FP"].notna()]
print(df_C['match_id'].count())
print(df_FP['match_id'].count())


20939
20939


In [9]:
# Drop unimportant columns
df_FP=df_FP.drop(['Starting_11','match_name','bowling_innings','prev_Overs_Bowled'],axis=1)

df_FPT=df_FPT.drop(['Starting_11','match_name','bowling_innings','prev_Overs_Bowled'],axis=1)


In [10]:
df_C=df_C.drop(['Starting_11'],axis=1)
df_CT=df_CT.drop(['Starting_11'],axis=1)

In [11]:
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder, KBinsDiscretizer

In [12]:
# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Define encoding function
def enc(df):
  df_FP["home_team"]=label_encoder.fit_transform(df_FP["home_team"])
  df_FP["batting_team_bat"]=label_encoder.fit_transform(df_FP["batting_team_bat"])
  df_FP["bowling_team_bowl"]=label_encoder.fit_transform(df_FP["bowling_team_bowl"])
  df_FP["away_team"]=label_encoder.fit_transform(df_FP["away_team"])
  df_FP["venue"]=label_encoder.fit_transform(df_FP["venue"])
  df_FP["Player_name"]=label_encoder.fit_transform(df_FP["Player_name"])

# Fit and transform the list of teams
enc(df_FP)
enc(df_FPT)
df_C["Captain/Vice Captain"]=label_encoder.fit_transform(df_C["Captain/Vice Captain"])
df_FP

match_id  season  home_team  away_team  venue  batting_innings  \
1             2    2008          7          1      7              2.0   
2             3    2008          1          0      0              1.0   
3             4    2008         12          1     28              1.0   
4             5    2008          4          1     11              2.0   
5             6    2008         10          1     17              2.0   
...         ...     ...        ...        ...    ...              ...   
21610     22357    2023          8         12     13              1.0   
21611     22358    2023          8         12     13              2.0   
21612     22359    2023          7         13     36              2.0   
21613     22360    2023         10          3     17              1.0   
21614     22361    2023          0          3     18              1.0   

       Player_name  bowling_team_bowl  batting_team_bat  prev_runs  ...  \
1                0                 14                 1       26.0  ...   
2                0                 14                 1       21.0  ...   
3                0                 14                 1        0.0  ...   
4                0                 14                 1       20.0  ...   
5                0                 14                 1        7.0  ...   
...            ...                ...               ...        ...  ...   
21610          644                 14                14        NaN  ...   
21611          644                 14                14        NaN  ...   
21612          644                 14                14        NaN  ...   
21613          644                 14                14        NaN  ...   
21614          644                 14                14        NaN  ...   

       prev_wickets  prev_conceded  prev_catches  prev_Dream Team  \
1               NaN            NaN           NaN              1.0   
2               NaN            NaN           1.0              0.0   
3               NaN            NaN           2.0              0.0   
4               NaN            NaN           0.0              1.0   
5               NaN            NaN           0.0              0.0   
...             ...            ...           ...              ...   
21610           NaN            NaN           NaN              0.0   
21611           NaN            NaN           NaN              0.0   
21612           NaN            NaN           NaN              0.0   
21613           NaN            NaN           NaN              0.0   
21614           NaN            NaN           NaN              0.0   

       prev_Total_FP  prev_overs  prev_fielding_heroics  prev_duck  luck  \
1               32.0         NaN                    NaN          0    35   
2               37.0         NaN                    0.0          0    79   
3               18.0         NaN                    0.0          1    33   
4               36.0         NaN                    1.0          0    82   
5               13.0         NaN                    1.0          0    54   
...              ...         ...                    ...        ...   ...   
21610           12.0         NaN                    NaN          0    10   
21611           20.0         NaN                    NaN          0     3   
21612           12.0         NaN                    NaN          0    80   
21613           12.0         NaN                    NaN          0     4   
21614           20.0         NaN                    NaN          0    57   

       Total_FP  
1          37.0  
2          18.0  
3          36.0  
4          13.0  
5          26.0  
...         ...  
21610      20.0  
21611      12.0  
21612      12.0  
21613      20.0  
21614      16.0  

[20939 rows x 23 columns]

In [13]:
df_C["Captain/Vice Captain"].value_counts()

Captain/Vice Captain
1    19333
2      815
0      791
Name: count, dtype: int64

In [14]:
# Fill nan values and engineer features
df_FP["prev_overs"].fillna(-0.1,inplace=True)
df_FP["balls"]=6*df_FP["prev_overs"].astype(int)+(df_FP["prev_overs"]-df_FP["prev_overs"].astype(int))*10
df_FPT["prev_overs"].fillna(-0.1,inplace=True)
df_FPT["balls"]=6*df_FPT["prev_overs"].astype(int)+(df_FPT["prev_overs"]-df_FPT["prev_overs"].astype(int))*10
print(df_FP["balls"].value_counts())

df_FP["prev_conceded"].fillna(-10, inplace=True)
df_FP["economy"] = (df_FP["prev_conceded"] + 1e-5) / (1e-5 + df_FP["balls"]) * 6
df_FPT["prev_conceded"].fillna(-10, inplace=True)
df_FPT["economy"] = (df_FPT["prev_conceded"] + 1e-5) / (1e-5 + df_FPT["balls"]) * 6
print(df_FP["economy"].value_counts())

df_FP["prev_runs"].fillna(1.0,inplace=True)
df_FP["prev_balls"].fillna(-2.0,inplace=True)
df_FPT["prev_runs"].fillna(1.0,inplace=True)
df_FPT["prev_balls"].fillna(-2.0,inplace=True)

balls
-1.0     9604
 24.0    6330
 18.0    2004
 12.0    1413
 6.0     1006
 22.0      80
 23.0      73
 20.0      57
 19.0      56
 21.0      54
 16.0      34
 17.0      34
 14.0      32
 13.0      31
 15.0      29
 7.0       17
 11.0      17
 5.0       12
 9.0       11
 1.0       10
 10.0      10
 2.0        8
 4.0        7
 8.0        6
 3.0        3
 0.0        1
Name: count, dtype: int64
economy
60.000540        9604
6.000000          473
6.750000          286
6.250000          269
7.249999          267
                 ... 
12.399996           1
6.272727            1
12.818179           1
600006.000000       1
17.249995           1
Name: count, Length: 494, dtype: int64


In [15]:
# Engineer new features
df_FP["strikerate"]=(1e-5+df_FP["prev_runs"])/(df_FP["prev_balls"]+1e-5)*100
df_FPT["strikerate"]=(1e-5+df_FPT["prev_runs"])/(df_FPT["prev_balls"]+1e-5)*100
print(df_FP["strikerate"].isnull().sum())
df_FP["strikerate"].value_counts()

0


strikerate
-50.000750     6240
 100.000000    1446
 0.001000       656
 50.000250      292
 0.000500       291
               ... 
 274.999891       1
 104.347825       1
 163.934416       1
 152.272715       1
 38.095268        1
Name: count, Length: 2065, dtype: int64

In [16]:
# Remove unused columns
df_FP = df_FP.drop(
    ["prev_overs", "prev_conceded", "prev_fours", "prev_sixes", "prev_runs"], axis=1
)
df_FPT = df_FPT.drop(
    ["prev_overs", "prev_conceded", "prev_fours", "prev_sixes", "prev_runs"], axis=1
)

In [17]:
# Checking changes
df_FP.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20939 entries, 1 to 21614
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   match_id               20939 non-null  int64  
 1   season                 20939 non-null  int64  
 2   home_team              20939 non-null  int64  
 3   away_team              20939 non-null  int64  
 4   venue                  20939 non-null  int64  
 5   batting_innings        20939 non-null  float64
 6   Player_name            20939 non-null  int64  
 7   bowling_team_bowl      20939 non-null  int64  
 8   batting_team_bat       20939 non-null  int64  
 9   prev_balls             20939 non-null  float64
 10  prev_wickets           11335 non-null  float64
 11  prev_catches           6682 non-null   float64
 12  prev_Dream Team        20939 non-null  float64
 13  prev_Total_FP          20939 non-null  float64
 14  prev_fielding_heroics  6682 non-null   float64
 15  prev_du

In [18]:
# Model performs better by dropping these columns

# # Filling nan values again
# df_FP["prev_fours"].fillna(-1,inplace=True)
# df_FP["prev_sixes"].fillna(-1,inplace=True)
# df_FP["boundaries"]=df_FP["prev_fours"]+df_FP["prev_sixes"]
# df_FPT["prev_fours"].fillna(-1,inplace=True)
# df_FPT["prev_sixes"].fillna(-1,inplace=True)
# df_FPT["boundaries"]=df_FPT["prev_fours"]+df_FPT["prev_sixes"]
# df_FP["boundaries"].value_counts()

In [19]:
# Filling nan values again
df_FP["prev_wickets"].fillna(-1,inplace=True)
df_FP["prev_fielding_heroics"].fillna(0,inplace=True)
df_FP["prev_catches"].fillna(0,inplace=True)
df_FPT["prev_wickets"].fillna(-1,inplace=True)
df_FPT["prev_fielding_heroics"].fillna(0,inplace=True)
df_FPT["prev_catches"].fillna(0,inplace=True)
df_FP["Total_FP"].value_counts().sort_index()

Total_FP
-4.0       11
-3.0        3
-2.0      219
-1.0       25
 0.0      185
         ... 
 233.0      1
 240.0      1
 252.0      1
 260.0      1
 306.0      1
Name: count, Length: 207, dtype: int64

In [20]:
(df_FP.isna().sum()).count()

21

In [21]:
df_FP

match_id  season  home_team  away_team  venue  batting_innings  \
1             2    2008          7          1      7              2.0   
2             3    2008          1          0      0              1.0   
3             4    2008         12          1     28              1.0   
4             5    2008          4          1     11              2.0   
5             6    2008         10          1     17              2.0   
...         ...     ...        ...        ...    ...              ...   
21610     22357    2023          8         12     13              1.0   
21611     22358    2023          8         12     13              2.0   
21612     22359    2023          7         13     36              2.0   
21613     22360    2023         10          3     17              1.0   
21614     22361    2023          0          3     18              1.0   

       Player_name  bowling_team_bowl  batting_team_bat  prev_balls  ...  \
1                0                 14                 1        21.0  ...   
2                0                 14                 1        17.0  ...   
3                0                 14                 1         1.0  ...   
4                0                 14                 1        22.0  ...   
5                0                 14                 1        12.0  ...   
...            ...                ...               ...         ...  ...   
21610          644                 14                14        -2.0  ...   
21611          644                 14                14        -2.0  ...   
21612          644                 14                14        -2.0  ...   
21613          644                 14                14        -2.0  ...   
21614          644                 14                14        -2.0  ...   

       prev_catches  prev_Dream Team  prev_Total_FP  prev_fielding_heroics  \
1               0.0              1.0           32.0                    0.0   
2               1.0              0.0           37.0                    0.0   
3               2.0              0.0           18.0                    0.0   
4               0.0              1.0           36.0                    1.0   
5               0.0              0.0           13.0                    1.0   
...             ...              ...            ...                    ...   
21610           0.0              0.0           12.0                    0.0   
21611           0.0              0.0           20.0                    0.0   
21612           0.0              0.0           12.0                    0.0   
21613           0.0              0.0           12.0                    0.0   
21614           0.0              0.0           20.0                    0.0   

       prev_duck  luck  Total_FP  balls   economy  strikerate  
1              0    35      37.0   -1.0  60.00054  123.809512  
2              0    79      18.0   -1.0  60.00054  123.529398  
3              1    33      36.0   -1.0  60.00054    0.001000  
4              0    82      13.0   -1.0  60.00054   90.909095  
5              0    54      26.0   -1.0  60.00054   58.333368  
...          ...   ...       ...    ...       ...         ...  
21610          0    10      20.0   -1.0  60.00054  -50.000750  
21611          0     3      12.0   -1.0  60.00054  -50.000750  
21612          0    80      12.0   -1.0  60.00054  -50.000750  
21613          0     4      20.0   -1.0  60.00054  -50.000750  
21614          0    57      16.0   -1.0  60.00054  -50.000750  

[20939 rows x 21 columns]

In [22]:
# To train the autogluon
x_train=df_FP.drop('Total_FP',axis=1)
y_train= pd.DataFrame()
y_train['Captain/Vice Captain']=df_C['Captain/Vice Captain']
y_train['Total_FP']=df_FP['Total_FP']
x_test= df_FPT

In [23]:
from sklearn.model_selection import train_test_split, cross_val_score

In [24]:
# To train custom models
x_train1, x_test1, y_train1, y_test1 = train_test_split(df_FP.drop('Total_FP',axis=1),pd.concat([df_C['Captain/Vice Captain'], df_FP['Total_FP']],axis=1), test_size=0.35, random_state=42)


In [25]:
x_train2=x_train1.drop(["home_team","batting_team_bat","bowling_team_bowl","away_team","venue","Player_name"],axis=1)


In [26]:
y_train

Captain/Vice Captain  Total_FP
1                         1      37.0
2                         1      18.0
3                         1      36.0
4                         1      13.0
5                         1      26.0
...                     ...       ...
21610                     1      20.0
21611                     1      12.0
21612                     1      12.0
21613                     1      20.0
21614                     1      16.0

[20939 rows x 2 columns]

In [27]:
x_train.columns

Index(['match_id', 'season', 'home_team', 'away_team', 'venue',
       'batting_innings', 'Player_name', 'bowling_team_bowl',
       'batting_team_bat', 'prev_balls', 'prev_wickets', 'prev_catches',
       'prev_Dream Team', 'prev_Total_FP', 'prev_fielding_heroics',
       'prev_duck', 'luck', 'balls', 'economy', 'strikerate'],
      dtype='object')

In [28]:
x_train.isnull().sum()

match_id                 0
season                   0
home_team                0
away_team                0
venue                    0
batting_innings          0
Player_name              0
bowling_team_bowl        0
batting_team_bat         0
prev_balls               0
prev_wickets             0
prev_catches             0
prev_Dream Team          0
prev_Total_FP            0
prev_fielding_heroics    0
prev_duck                0
luck                     0
balls                    0
economy                  0
strikerate               0
dtype: int64

In [29]:
# Train the FFNN model
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
import numpy as np

seed = 61
tf.random.set_seed(seed)
# Define the model
model = Sequential()

# Input layer with 13  neurons
model.add(Dense(100, input_dim=13, activation='relu'))

# Hidden layer 1
model.add(Dense(50, activation='relu'))
model.add(Dropout(0.4))

# Hidden layer 2
model.add(Dense(30, activation='relu'))
model.add(Dropout(0.3))

# Hidden layer 3
model.add(Dense(15, activation='relu'))
model.add(Dropout(0.5))

# Output layer with 1 neuron
model.add(Dense(1, activation='linear'))

# Compile the model
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)

# Compile the model with the specified optimizer and loss function
model.compile(optimizer=optimizer, loss='mean_squared_error')

# Summary of the model
model.summary()

# Normalize the data
scaler_X = MinMaxScaler()

X_scaled = scaler_X.fit_transform(x_train2.drop('match_id',axis=1))
# Train the model
model.fit(X_scaled, y_train1["Total_FP"], epochs=35, batch_size=10, validation_split=0.2)





Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 100)               1400      
                                                                 
 dense_1 (Dense)             (None, 50)                5050      
                                                                 
 dropout (Dropout)           (None, 50)                0         
                                                                 
 dense_2 (Dense)             (None, 30)                1530      
                                                                 
 dropout_1 (Dropout)         (None, 30)                0         
                                                                 
 dense_3 (Dense)             (None, 15)                465       
                                                                 
 dropout_2 (Dropout)         (None, 15)                0

In [30]:
x_test.fillna(x_test['prev_Total_FP'].mean(),inplace=True)

In [47]:
y_pred_FP= model.predict(scaler_X.transform(x_test1.drop(['match_id',"home_team","batting_team_bat","bowling_team_bowl","away_team","venue","Player_name"],axis=1)))
np.unique(y_pred_FP)

230/230 [==============================] - 0s 2ms/step


array([  36.721794,   36.724586,   36.725372, ...,   46.9892  ,
         47.51162 , 1349.157   ], dtype=float32)

In [48]:
y_pred_FP


array([[41.81332 ],
       [40.531796],
       [36.721794],
       ...,
       [36.721794],
       [39.958065],
       [36.721794]], dtype=float32)

In [50]:
y_pred= model.predict(scaler_X.transform(x_test1.drop(['match_id',"home_team","batting_team_bat","bowling_team_bowl","away_team","venue","Player_name"],axis=1)))
rmse = np.sqrt(mean_squared_error(y_test1["Total_FP"], y_pred))
print("RMSE:", rmse)

230/230 [==============================] - 1s 2ms/step
RMSE: 35.2742754836611


In [34]:
!pip install imbalanced-learn
from imblearn.over_sampling import SMOTE

In [35]:
smote = SMOTE(sampling_strategy='auto', random_state=42)

X_resampled, y_resampled = smote.fit_resample(x_train1,y_train1['Captain/Vice Captain'])

In [36]:
y_resampled.value_counts()

Captain/Vice Captain
1    12582
2    12582
0    12582
Name: count, dtype: int64

In [37]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

# Initialize classifiers
classifiers = {
    "Random Forest": RandomForestClassifier(n_estimators=41,
        max_depth=60,
        bootstrap=True,
        max_features='sqrt',
        class_weight='balanced',
        criterion='gini',
        random_state=40),
    "Decision_tree_classifier":DecisionTreeClassifier(criterion='gini',
                                                      max_depth=8,
                                                      max_features=None,
                                                      random_state=60)
}

for clf_name, clf in classifiers.items():
    clf.fit(X_resampled.drop('match_id',axis=1), y_resampled)
    y_pred_C = clf.predict(x_test1.drop('match_id',axis=1))
    y_pred = clf.predict(x_test1.drop('match_id',axis=1))

    print(classification_report(y_test1['Captain/Vice Captain'], y_pred))
    print(confusion_matrix(y_test1['Captain/Vice Captain'], y_pred))
    accuracy = accuracy_score(y_test1['Captain/Vice Captain'], y_pred)
    print("Accuracy:", accuracy*100)

              precision    recall  f1-score   support

           0       0.06      0.00      0.01       294
           1       0.92      1.00      0.96      6751
           2       0.00      0.00      0.00       284

    accuracy                           0.92      7329
   macro avg       0.33      0.33      0.32      7329
weighted avg       0.85      0.92      0.88      7329

[[   1  293    0]
 [  17 6727    7]
 [   0  284    0]]
Accuracy: 91.79969982262246
              precision    recall  f1-score   support

           0       0.08      0.09      0.08       294
           1       0.92      0.92      0.92      6751
           2       0.04      0.04      0.04       284

    accuracy                           0.86      7329
   macro avg       0.35      0.35      0.35      7329
weighted avg       0.86      0.86      0.86      7329

[[  25  255   14]
 [ 283 6236  232]
 [  17  256   11]]
Accuracy: 85.57784145176696


In [38]:
y_pred_C.shape

(7329,)

In [46]:
y_pred_FP.shape

(709, 1)

In [39]:
cap_pred=[]

In [40]:
for i in y_pred_C:
  if(i==0):
    cap_pred.append('C')
  elif (i==1):
    cap_pred.append('NC')
  else:
    cap_pred.append('VC')

In [51]:
submission = pd.DataFrame()
submission['match_id']= x_test1['match_id']
submission['Total_FP']=y_pred_FP
submission['Captain/Vice Captain']= cap_pred

In [ ]:
# Adding the autogluon model:
!pip install autogluon
!pip install --upgrade mxnet
from autogluon.tabular import TabularPredictor

In [ ]:
# Fit the model using AutoGluon
predictor = TabularPredictor(label="Captain/Vice Captain").fit(
    df_C,
    presets="high_quality",
    ag_args_fit={"num_gpus": 1},
    ag_args_ensemble=dict(fold_fitting_strategy="sequential_local")
)

In [ ]:
# Refit complete, total runtime = 156.59s ... Best model: "WeightedEnsemble_L2_FULL"
# TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels\ag-20240602_175553")
predictor = TabularPredictor.load("/content/AutogluonModels/ag-20240604_132213")
# Make predictions on the test data
y_pred = predictor.predict(x_test1.drop('match_id',axis=1))

# Calculate accuracy
accuracy = (y_pred == df_C["Captain/Vice Captain"]).mean()
print(f"Accuracy: {accuracy}")